/**
 * Build script: compiles TypeScript source and emits both ESM and CJS bundles.
 * Run: node scripts/build.js
 *
 * Steps:
 *   0. Generate src/_base-css.ts  from src/styles.css
 *   1. Clean dist/
 *   2. Compile ESM via tsc
 *   3. Compile CJS via tsc (temp tsconfig)
 *   4. Bundle everything into single-file ESM + CJS
 *   5. Copy .d.ts files and src/styles.css → dist/
 *   6. Cleanup intermediate files
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const SRC  = path.join(ROOT, 'src');

// ── 0. Generate _base-css.ts from styles.css ──────────────────────────────
console.log('[build] Generating _base-css.ts...');
const cssSource = fs.readFileSync(path.join(SRC, 'styles.css'), 'utf8');
// Escape backticks and ${} template expressions inside the CSS string
const cssEscaped = cssSource.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const baseCssTs = [
  '// AUTO-GENERATED by scripts/build.js — do not edit manually.',
  '// Edit src/styles.css instead and re-run npm run build.',
  `export const BASE_CSS = \`${cssEscaped}\`;`,
  '',
].join('\n');
fs.writeFileSync(path.join(SRC, '_base-css.ts'), baseCssTs, 'utf8');

// ── 1. Clean dist ──────────────────────────────────────────────────────────
if (fs.existsSync(DIST)) {
  fs.rmSync(DIST, { recursive: true, force: true });
}
fs.mkdirSync(DIST, { recursive: true });
// ── 2. Compile ESM (default tsconfig) ─────────────────────────────────────
console.log('[build] Compiling ESM...');
execSync('npx tsc --project tsconfig.json', {
  cwd: ROOT,
  stdio: 'inherit',
});

// ── 3. Compile CJS (write a temp tsconfig) ────────────────────────────────
console.log('[build] Compiling CJS...');
const tsconfigCjs = {
  compilerOptions: {
    target: 'ES2017',
    module: 'CommonJS',
    moduleResolution: 'node',
    lib: ['ES2017', 'DOM'],
    declaration: false,
    outDir: './dist/cjs',
    strict: true,
    esModuleInterop: true,
    skipLibCheck: true,
    sourceMap: false,
  },
  include: ['src'],
  exclude: ['node_modules', 'dist'],
};
const tmpTsconfig = path.join(ROOT, 'tsconfig.cjs.json');
fs.writeFileSync(tmpTsconfig, JSON.stringify(tsconfigCjs, null, 2));
try {
  execSync('npx tsc --project tsconfig.cjs.json', {
    cwd: ROOT,
    stdio: 'inherit',
  });
} finally {
  fs.unlinkSync(tmpTsconfig);
}

// ── 4. Bundle into single files ────────────────────────────────────────────
console.log('[build] Bundling files...');
buildSingleFileBundle();

function buildSingleFileBundle() {
  // Files in dependency order: _base-css → styles → index
  const SOURCE_FILES = ['_base-css', 'styles', 'index'];

  // ── ESM bundle ────────────────────────────────────────────────────────
  const esmDir = path.join(DIST, 'esm');
  let esmParts = ['// @tavosud/floating-button-whatsapp-modern - ESM bundle\n'];

  for (const name of SOURCE_FILES) {
    const filePath = path.join(esmDir, `${name}.js`);
    if (!fs.existsSync(filePath)) {
      console.error(`[build] Missing ESM file: ${filePath}`);
      process.exit(1);
    }
    let code = fs.readFileSync(filePath, 'utf8');
    // Remove all local imports
    code = code.replace(/^import\s[^'"]*from\s+['"]\.\/_?[^'"]+['"]\s*;?\s*$/gm, '');
    // Remove export keywords from non-index files to avoid re-declaration
    if (name !== 'index') {
      code = code.replace(/^export\s+(?:function|class|const|let|var|interface|type)\s/gm, (m) =>
        m.replace('export ', ''));
      code = code.replace(/^export\s*\{[^}]*\}\s*;?\s*$/gm, '');
    }
    esmParts.push(code.trim());
  }

  fs.writeFileSync(path.join(DIST, 'index.esm.js'), esmParts.join('\n\n'), 'utf8');

  // ── CJS bundle ────────────────────────────────────────────────────────
  const cjsDir = path.join(DIST, 'cjs');
  let cjsParts = ['"use strict";\n// @tavosud/floating-button-whatsapp-modern - CJS bundle\n'];

  for (const name of SOURCE_FILES) {
    const filePath = path.join(cjsDir, `${name}.js`);
    if (!fs.existsSync(filePath)) {
      console.error(`[build] Missing CJS file: ${filePath}`);
      process.exit(1);
    }
    let code = fs.readFileSync(filePath, 'utf8');
    // Remove "use strict" (already at top)
    code = code.replace(/^["']use strict["']\s*;?\s*$/gm, '');
    // Remove Object.defineProperty(exports, "__esModule", ...) lines
    code = code.replace(/^Object\.defineProperty\(exports,\s*["']__esModule["'][^)]*\)\s*;?\s*$/gm, '');
    // Remove require() calls to local modules
    code = code.replace(/^(?:const|let|var)\s+\S+\s*=\s*require\(['"]\.\/_?[^'"]+['"]\)\s*;?\s*$/gm, '');
    if (name !== 'index') {
      // Remove exports.xxx = ... lines from helper files (they'll be inlined)
      code = code.replace(/^exports\.\w+\s*=.*$/gm, '');
    }
    cjsParts.push(code.trim());
  }

  // Fix namespace references: e.g. styles_1.buildInstanceStyles → buildInstanceStyles
  let cjsBundle = cjsParts.join('\n\n');
  cjsBundle = cjsBundle.replace(/\b\w+_\d+\.\b/g, '');

  fs.writeFileSync(path.join(DIST, 'index.cjs.js'), cjsBundle, 'utf8');
}

// ── 5. Copy declaration files + standalone CSS ─────────────────────────────
const dtsIndex = path.join(DIST, 'esm', 'index.d.ts');
const dtsTypes  = path.join(DIST, 'esm', 'types.d.ts');

if (fs.existsSync(dtsIndex)) fs.copyFileSync(dtsIndex, path.join(DIST, 'index.d.ts'));
if (fs.existsSync(dtsTypes))  fs.copyFileSync(dtsTypes,  path.join(DIST, 'types.d.ts'));

// Copy standalone CSS for users who prefer to import it manually
fs.copyFileSync(path.join(SRC, 'styles.css'), path.join(DIST, 'floating-button-whatsapp-modern.css'));

console.log('[build] Done. Output: dist/index.esm.js, dist/index.cjs.js, dist/index.d.ts, dist/floating-button-whatsapp-modern.css');

// ── 6. Cleanup intermediate folders ───────────────────────────────────────
fs.rmSync(path.join(DIST, 'esm'), { recursive: true, force: true });
fs.rmSync(path.join(DIST, 'cjs'), { recursive: true, force: true });
['index.js', 'styles.js', 'types.js', '_base-css.js', 'styles.d.ts', '_base-css.d.ts'].forEach(f => {
  const fp = path.join(DIST, f);
  if (fs.existsSync(fp)) fs.unlinkSync(fp);
});

